### ISSUE TITLE
Make CC Global Header work even if WordPress permalinks are not enabled

### ISSUE THREAD

**Issue by brylie** [creativecommons/cc-global-components#10]
As currently written, the CC Global Header requires that WordPress permalinks are enabled.

> One more thing that just came to mind, since we used the API `requestPath` for the Global Header component as `/wp-json/ccnavigation/menu` this means the WP service it is calling has to use any of the other Permalink types except `plain`. Preferably `post name`. I think we can include this too in the `README.md`?

_Originally posted by @MuluhGodson in https://github.com/creativecommons/cc-global-components/issues/9#issuecomment-990792665_

However, we may want to make the CC Global Header resilient in case the permalinks are not enabled, such as in a development environment. For example, we might call the non-permalink API endpoint in all cases, since it should work even if permalinks are enabled.

**Comment by MuluhGodson** [comment]
The non-permalink API endpoint works regardless of if permalinks are enabled or not. This should be the default mode.
