### ISSUE TITLE
Document purpose(s) and scope for each CC Component and re-consider naming convention(s)

### ISSUE THREAD

**Issue by brylie** [creativecommons/cc-global-components#24]
The CC Global Components project is at a confluence of several experiments, tasks, and discussions related to the CreativeCommons.org website redesign. As the waters are a bit fast-moving, clarity and direction may be a bit muddied. 

Now that we have traversed a period of rapid development, we can pause to recompose ourselves to make sure we are still on the desired course.

Let's take some time to document the purpose(s) for each of the CC Global Components and reassess naming conventions. That way, our next release can include this richer documentation and purposeful direction.

## Related issue(s)

- #22

## Original comment

> I left a comment on another ticket that relates to the above discussion, dropping here for reference: https://github.com/creativecommons/project_creativecommons.org/issues/149#issuecomment-993538956
>
> I am also struck that somewhere along the way we (the broader team, over the last many months, likely) lost consistency with how we reference different components.
>
> I will work to adjust how I am referring to things as it is likely leading to confusion, but just to summarize:
>
> CC Global Header = was intended to only refer to the other-site link on the expandable black-background section, that would sit above the site header/navigation. It appears that this is now being called the "CC Explore" header.
>
> Site header/Site navigation = was intended to refer to the logo and on-site navigation. This was not intended to be a "global component" necessarily. However, finding ways to cleanly pull this in/include in global components has become the preferred way to show seamless navigation between the parts of CC.org that run on WordPress and those that do not. It appears this is now being called the "CC Global Header", potentially? This (as indicated in my comment linked above) is definitely not "global" in that it should be the same across multiple CC web properties. Essentially, if we just think about URLs, they _each_ share the same navigation, but not between each others. E.g.:
CreativeCommons.org = has multiple things happening under the hood, all should have the same site navigation
CC Summit = has its own logo and site navigation
CC Certificates = in the future, will have its own logo and site navigation, might have multiple different things happening behind the scenes (i.e. base site may be WordPress, the course content may be on a different education-specific publishing platform, tbd)
... and so forth.
>
> CC Global Footer = I think we're all using the same language here, this is the black-background footer that is on every page designed for CC.org and will also be used across other CC web properties.
>
_Originally posted by @annatuma in https://github.com/creativecommons/cc-global-components/issues/12#issuecomment-993554354_

**Comment by brylie** [comment]
One small-ish improvement might be to avoid using the word "global" in any sub-component for both terseness and to reflect the situated nature of the components. E.g.,

- `cc-header` - is composed of sub-elements like navigation and menu that changes based on context
    - `cc-navigation` - shows navigation items that are relevant to the place it is embedded, e.g., CreativeCommons.org/Licenses or  Summit
    - `cc-logo` - may be configurable to display alternative logos like CC Open Source or CC Summit

**Comment by possumbilities** [comment]
Closing this, issues related to this would have been resolved in the new Vocabulary, currently in development within [index-prototype](https://github.com/creativecommons/index-prototype)
