### ISSUE TITLE
Enable automation for NPM packag publication

### ISSUE THREAD

**Issue by brylie** [creativecommons/cc-global-components#29]
## Problem

We currently need to publish an NPM package after each release manually.

## Description

Ideally, there would be some degree of automation when creating new project releases.

## Alternatives

We can continue publishing the NPM package manually.

## Additional context

- GitHub Actions: Publishing Node.js packages - [Publishing packages to the npm registry](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry)

**Comment by possumbilities** [comment]
Closing this, as this is being archived this is no longer on the roadmap.
