### ISSUE TITLE
[Feature] Documentation site for CC Global Components

### ISSUE THREAD

**Issue by MuluhGodson** [creativecommons/cc-global-components#30]
## Problem

The CC Global components as of now lack a proper documentation site that can be consulted by other developers and users.

## Description

@brylie suggested we use [VuePress](https://v2.vuepress.vuejs.org/) which is a perfect fit as it has native support for Vue components and it is easy to setup. 

## Alternatives

Use the README.md

**Comment by possumbilities** [comment]
Closing this, as this is being archived, this is no longer on the roadmap.
