### ISSUE TITLE
Render Multi-Level Nav Items

### ISSUE THREAD

**Issue by MuluhGodson** [creativecommons/cc-global-components#38]
## Problem

The CC desired [menu structure](https://docs.google.com/document/d/1TmNoMO6q_lVeOeuxZy15FGmTbVyl2tv1SJegccxZ8Tw/edit) has Menu items with 2 sub-level menu items. Currently, the CC Global Header can only render menu items with  1 sub menu.

## Alternatives
We may consider returning HTML via the API call instead of a JSON object.

**Comment by sanjeevbhusal** [comment]
anyone assigned for it?

**Comment by brylie** [comment]
@sanjeevbhusal, nobody is currently assigned. We are considering how to proceed.

What are your thoughts on Bulma multi-level navigation menus?

**Comment by MuluhGodson** [comment]
Originally comment [creativecommons/creativecommons-base#56](https://github.com/creativecommons/creativecommons-base/pull/170#issuecomment-1033569115)

The idea basically is to reduce the number of nested loops, since basically each level or sub-menu requires a loop of its own and maybe some sort of recursive function. I don't think this is very ideal. The most optimum solution will be one which will not require us to alter the CC Global Menu web component each time there's a modification on the Menus on WordPress. 

Currently the function which the API calls is found here [creativecommons/wp-theme-creativecommons.org/inc/filters.php#L14](https://github.com/creativecommons/wp-theme-creativecommons.org/blob/d25fc2a4fecc4157ea6d4873b2fcb706beab93f7/inc/filters.php#L14) and if I recall correctly we had to modify this function to be able to have the API return sub-menus. This means for the two-level sub-menus we currently have, we may have to further rewrite this function yet with another loop to add the level 2 sub-menus to the level 1 sub-menus which is all added to the top-level menus. On the CC Global side, we'll also have to add an extra loop for the level 2 sub-menus since we currently have just a loop for Top menus and their direct child-menus. 

I've been tinkering, replacing the above function with the WordPress function `wp_nav_menu` returns an HTML output.

```php
public static function get_header_menu() {
    $header_menu_items = wp_nav_menu(
      array(
        'theme_location'  => 'main-navigation',
        'depth'           => 0,
        'container'       => 'div',
        'container_class' => 'navbar-menu',
        'items_wrap'      => '<div id="%1$s" class="navbar-end">%3$s</div>',
        'menu_class'      => 'navbar-menu',
        'menu_id'         => 'primary-menu',
        'after'           => '</div>',
        'walker'          => new Navwalker(),
      )
    );
    return $header_menu_items;
  }
```
//// Results of the API call
![image](https://user-images.githubusercontent.com/40151808/153170983-551a22d1-c9b6-4699-b811-e8187eeedac5.png)

With this output, on the Vue side, we can just have a simple `div` element with a `v-html` directive and have all the menus rendered without any loops.

**Comment by MuluhGodson** [comment]
With more discussion here [project_creativecommons.org#Issue-224](https://github.com/creativecommons/project_creativecommons.org/issues/224). I am moving this to `post launch` and removing it from the current sprint.

**Comment by brylie** [comment]
@MuluhGodson, should we close this issue?
