### ISSUE TITLE
[Feature] Add CC Donation Modal to the CC Global Components

### ISSUE THREAD

**Issue by MuluhGodson** [creativecommons/cc-global-components#5]
## Problem
We have previously used Google Tag Manager to define a donation appeal pop-up. Following from this (comment)[https://github.com/creativecommons/project_creativecommons.org/issues/186#issuecomment-984545850], 
@brylie suggested that:
> Alternatively, this might be a good addition to the cc-global-components collection, since it is just JavaScript, HTML, and CSS.

 - [x] Develop a component for the Donation Modal
 - [x] Set a cookie when the user closes the modal (by clicking close or outside of the modal)
 - [x] The cookie should expire after five days

## Description
Adding the Donation Modal to the CC Global Components is advantageous given that it will be distributed via CDN making it easier to deploy on any of the CC Web properties. 

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Closing this, issues related to this would have been resolved in the new Vocabulary, currently in development within [index-prototype](https://github.com/creativecommons/index-prototype)
